name: MolRep
channels:
  - rdkit
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py37h7b6447c_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.1.19=h06a4308_1
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.4=py37h261ae71_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.19.0=py37hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py37_0
  - jinja2=2.11.2=py_0
  - joblib=1.0.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.0=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.73.0=hf484d3e_11
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markupsafe=1.1.1=py37h14c3975_1
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nb_conda=2.2.1=py37_0
  - nb_conda_kernels=2.3.1=py37h06a4308_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - notebook=6.1.6=py37h06a4308_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandas=1.2.0=py37ha9443f7_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.0=py37he98fc37_0
  - pip=20.3.3=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-boost=1.73.0=py37h04863e7_11
  - pycparser=2.20=py_2
  - pygments=2.7.4=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - pyrsistent=0.17.3=py37h7b6447c_0
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - pytz=2020.5=pyhd3eb1b0_0
  - pyzmq=20.0.0=py37h2531618_1
  - rdkit=2020.09.1.0=py37hd50e099_1
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.5.2=py37h0b6359f_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=51.1.2=py37h06a4308_4
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.2=py37h06a4308_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - ase==3.21.0
    - cached-property==1.5.2
    - chardet==4.0.0
    - cycler==0.10.0
    - future==0.18.2
    - googledrivedownloader==0.4
    - greenlet==1.0.0
    - h5py==3.1.0
    - idna==2.10
    - ipython-sql==0.4.0
    - isodate==0.6.0
    - kiwisolver==1.3.1
    - llvmlite==0.35.0
    - matplotlib==3.3.3
    - networkx==2.4
    - numba==0.52.0
    - numpy==1.19.5
    - parso==0.8.1
    - scikit-optimize==0.8.1
    - prettytable==0.7.2
    - psycopg2-binary==2.8.6
    - python-louvain==0.15
    - pyyaml==5.4.1
    - rdflib==5.0.0
    - requests==2.25.1
    - sqlalchemy==1.4.1
    - sqlparse==0.4.1
    - tqdm==4.56.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - xgboost==1.3.3
